export enum UserEventTypeEnum {
  CREATE = 'CREATE',
  UNREGISTER = 'UNREGISTER',
  VERIFY = 'VERIFY',
  FIRST_SIGNIN = 'FIRST_SIGNIN',
  EXISTS_ON_OTHER_PROVIDER = 'EXISTS_ON_OTHER_PROVIDER',
  PASSWORD_RESET = 'PASSWORD_RESET',
  VERIFICATION_EMAIL_SENT = 'VERIFICATION_EMAIL_SENT',
}
